# Custom Language File for Launcher Customizer

[ejs.app]
title = "Medovukha Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/bayergg/MedovukhaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/wrRyNNzD"

[ejs.settings]
sourceGithubLink = "https://github.com/bayergg/MedovukhaLauncher"
supportLink = "https://github.com/bayergg/MedovukhaLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MEDOVUKHA"
welcomeDescription = ""
welcomeDescCTA = ""
